# You can create your own laguage files in the "languages" folder.
# Already made languages:
#  en-US
#  pt-BR
lang: "en-US"

# This determines if the fly future will be activated on the server.
# Obs: You need to reload the server if you want to change this value.
fly-enabled: true

# Sound to play when player toggles flight mode.
fly-sound:
  sound: "BLOCK_NOTE_BLOCK_BASS"
  volume: 1.0
  pitch: 1.0

# Sound to play whenever an error happens.
error-sound:
  sound: "ENTITY_ENDERMAN_TELEPORT"
  volume: 1
  pith: 1

# Worlds where the plugin is active.
# Obs: If you want to disable on all worlds
# let the list like this:
# worlds-whitelist:
#   - ""
worlds-whitelist:
  - world